### ISSUE TITLE
Icons are not displayed if initially hidden

### ISSUE THREAD

**Issue by HenriPodolski** [jannicz/svg-icon-sprite#6]
If DOM for icons is loaded later, e.g. after user interaction, then the icons are not loaded. DOM looks like that:
![image](https://user-images.githubusercontent.com/96691/75116336-861eb100-5667-11ea-9c3c-eb5e57920c4e.png)
Notice that the xlink href is undefined.

Also the size the custom element takes in this situation is huge and it breaks the whole page layout. If you already have an idea how this can be solved and do not have time to fix it on your own, I can offer help.

**Comment by jannicz** [comment]
I added a new example where the icon is inserted into the DOM after a user interaction:
https://jannicz.github.io/svg-icon-sprite/examples/onload.html

I cannot observe a wrong behavior - how would i construct the example to better match your case?

**Comment by HenriPodolski** [comment]
It seems that this was an issue with Angular and standard attributes. If I change this:
`<svg-icon
        aria-hidden="true"
        class="modal-container__info-icon"
        [src]="'assets/sprites/sprite.svg#info'"
        [width]="'20px'"
        [height]="'20px'"
        [viewBox]="'0 0 20 20'"
      ></svg-icon>`
to this
`<svg-icon
        aria-hidden="true"
        class="modal-container__info-icon"
        [attr.src]="'assets/sprites/sprite.svg#info'"
        [attr.width]="'20px'"
        [attr.height]="'20px'"
        [attr.viewBox]="'0 0 20 20'"
      ></svg-icon>
` 
then it works.
